[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
[options="header", cols="1,3,1"]
|===
|Quality goal
|Scenario
|Priority

|Usability
|A user should be able to select a contact and start the conversation in less than 
5 seconds.
|High, High

|Performance efficiency
|The message should be sent and stored in the other user's POD in less than 2 
seconds.
|High, Medium

|Security
|In case of a network failure, the system should notify the user about having 
no connection in less than 4 seconds.
|High, Low

|Testability
|When testing a piece of the design, we should be able to finish in less than 
3 days.
|Medium, High

|Usability
|If a user deletes a message by accident, the system should be able to recover it 
in less than 5 seconds.
|Medium, Low
|===
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header"]
|===
|Role/Name|Expectations
| Solid development team | They are the original proposers of the project, and are interested in the best results of this and the ones of other teams of this course, as the best ones will be presented for public review and maybe used in the final product. For more information, see https://solid.mit.edu/.
| Teachers of the cousrse | They expect a well developed final version following some specific guidelines, paying special attention to the architecture of the project, due to this being the main topic of the subject.
|===
