[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

[options="header", cols=2*]
.Technical
|===
| Name         
| Definition

| Decentralized
| The system will be based on a decentralized architecture 
where data storage is separated from the app.

| Data Storage  
| The data must be stored in the user's pods.

| Sharing files
| Users must be able to share pictures, videos or other kinds 
of files with other friends through the chat.

| Notifications
| Users must receive notifications when some friend wants to chat 
with them.

| Groups
| Users can have groups of friends where everyone involved must be 
able to chat.

| Live calls
| Users can have live calls.

| Video calls
| Users can have video calls.

| Screen sharing
| Users can share their screens in the chat.
|===
