[[section-technical-risks]]
== Risks and Technical Debts

- The development team footnote:[Not necessarily refering to the abolute totality of the members of the team, but to the majority of it. Applicable to the rest of this piece of documentation.] has never designed and implemented an aplication related to the use of Solid pods, so they have to get used to how this technology works, which is translated into time spent learning how they work, subtracting time from development.
- The development team has never worked with Angular, so there is the risk that the team is not able to adapt themselves how to work with this framework, or it would take them time, that at last, this time is going to be reduced from development time.
- The development team has never designed an architecture for an application, and they are learning how to do it at the same time, so there is the risk that the architecture designed for this project is not as optimal as it should be, deriving in a poor design of the project, which could hinder the development.
- The majority of the group has never worked with RDF, which can be complex to understand, and to design structures and classes with it, so there is the risk that the design of the application from the point of view of translating the data to RDF, is not very efficient, or is not working properly.
- Until now, the team, has not worked with continuous integration, therefore, there is te risk of not adapting properly to this way of working, or not doing it as it should be done. We have to spend time checking that we are doing this part correctly.
- In the past, the members of the team have worked with relational databases as HSQLDB or oracle, and they are not used to using the NoSQL database engine MongoDB, which can derive into a poor database design.
- The team has never used Mocha for implementing tests in JavaScript, and that could mean that, at first, tests may not be as good as they should, because the team need time to adapt its work to this technology.
- Until now, in the projects the members of the team had to face, they never had to do documentation as the one required for this project, which could subtract time of development, because they have to do a lot of research about how to do this type of documentation properly.
