language: node_js
sudo: false
node_js:
  - 8

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules
    - ./coverage/lcov.info

install:
  - npm install
  
script:
  - npm run test -- --watch=false --browsers=ChromeHeadlessCI

after_success:
  - ls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
